import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;


public class basic_pay extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs,rs1 = null;
    PreparedStatement ps,ps1 = null;
    public basic_pay() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/4,dim.height/4);
        this.setTitle("Basic Pay");
        initComponents();
        conn = javaConnect.ConnectDb();
        employeeList();
        Image img = getToolkit().getImage("C:\\Users\\Wango\\Documents\\NetBeansProjects\\payroll\\src\\lg.png");
        Image newimg = img.getScaledInstance(500, 500,  java.awt.Image.SCALE_SMOOTH);
        this.setIconImage(newimg);
    }
    public void close(){
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        basic_pay = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Basic Pay"); // NOI18N
        setPreferredSize(new java.awt.Dimension(710, 350));
        setResizable(false);

        jLabel1.setText("Employee :");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setText("Earned Amount :");

        basic_pay.setText("0.00");
        basic_pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                basic_payKeyReleased(evt);
            }
        });

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(basic_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(cancel)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(basic_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_cancelActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jList1ValueChanged

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        try{
        if(jList1.isSelectionEmpty()){
        JOptionPane.showMessageDialog(null, "Please select Employee!");
        System.out.println("nothing");
        }else{
        String ename = jList1.getSelectedValue().toString();
        int index = jList1.getSelectedIndex();
          
        String[] parts = ename.split(" ",2);
        String part1 = parts[0]; // 004
        String part2 = parts[1]; 
        String e_id = "select * from employee where personal_file_number = '"+part1+"'";
        ps1 = conn.prepareStatement(e_id);
        rs1 = ps1.executeQuery();

        if(rs1.next()){
        String eid = rs1.getString("id");
        if(basic_pay.getText().matches("\\-?\\d+") == false && basic_pay.getText().matches("^[-+]?\\d+(\\.{0,1}(\\d+?))?$") == false) {
        JOptionPane.showMessageDialog(null,"Please provide numbers only for basic pay!");
        }else{
        String sql = "update employee set basic_pay='"+basic_pay.getText()+"' where id = '"+eid+"'";
        ps = conn.prepareStatement(sql);
        ps.execute();
        JOptionPane.showMessageDialog(null, "Successfully updated employee basic salary");
        }
        }
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_okActionPerformed

    private void basic_payKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basic_payKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         try{
        if(jList1.isSelectionEmpty()){
        JOptionPane.showMessageDialog(null, "Please select Employee!");
        System.out.println("nothing");
        }else{
        String ename = jList1.getSelectedValue().toString();
        int index = jList1.getSelectedIndex();
          
        String[] parts = ename.split(" ",2);
        String part1 = parts[0]; // 004
        String part2 = parts[1]; 
        String e_id = "select * from employee where personal_file_number = '"+part1+"'";
        ps1 = conn.prepareStatement(e_id);
        rs1 = ps1.executeQuery();

        if(rs1.next()){
        String eid = rs1.getString("id");
        if(basic_pay.getText().matches("\\-?\\d+") == false && basic_pay.getText().matches("^[-+]?\\d+(\\.{0,1}(\\d+?))?$") == false) {
        JOptionPane.showMessageDialog(null,"Please provide numbers only for basic pay!");
        }else{
        String sql = "update employee set basic_pay='"+basic_pay.getText()+"' where id = '"+eid+"'";
        ps = conn.prepareStatement(sql);
        ps.execute();
        JOptionPane.showMessageDialog(null, "Successfully updated employee basic salary");
        }
        }
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_basic_payKeyReleased
    }
     private void employeeList(){
    DefaultListModel lm = new DefaultListModel();
    
    try {
    String sql = "SELECT * FROM employee";
    ps = conn.prepareStatement(sql);
    rs = ps.executeQuery();
    
    while(rs.next()){
        String add = rs.getString("personal_file_number");
        String add1 = rs.getString("first_name");
        String add2 = rs.getString("last_name");
        String concat = add+"                             |" +add1+ "                                   |"  + add2;
        lm.addElement(concat);
    }
      jList1.setModel(lm);
      DefaultListCellRenderer r = (DefaultListCellRenderer)jList1.getCellRenderer();
        r.setHorizontalAlignment(SwingConstants.LEFT);
    } catch (Exception e) {
    e.printStackTrace();
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basic_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basic_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basic_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basic_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basic_pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basic_pay;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
