import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;


public class basic_comission extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs,rs1,rs2,rs3,rs4,rs5 = null;
    PreparedStatement ps,ps1,ps2,ps3,ps4,ps5 = null;
    public basic_comission() {
     Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/4,dim.height/4);
        this.setTitle("Commission");
        initComponents();
        conn = javaConnect.ConnectDb();
        employeeList();
        Image img = getToolkit().getImage("C:\\Users\\Wango\\Documents\\NetBeansProjects\\payroll\\src\\lg.png");
        Image newimg = img.getScaledInstance(500, 500,  java.awt.Image.SCALE_SMOOTH);
        this.setIconImage(newimg);
    }

    private void employeeList(){
    DefaultListModel lm = new DefaultListModel();
    
    try {
    String sql = "SELECT * FROM employee";
    ps = conn.prepareStatement(sql);
    rs = ps.executeQuery();
    
    while(rs.next()){
        String add = rs.getString("personal_file_number");
        String add1 = rs.getString("first_name");
        String add2 = rs.getString("last_name");
        String concat = add+"                             |" +add1+ "                                   |"  + add2;
        lm.addElement(concat);
    }
      jList1.setModel(lm);
      DefaultListCellRenderer r = (DefaultListCellRenderer)jList1.getCellRenderer();
        r.setHorizontalAlignment(SwingConstants.LEFT);
    } catch (Exception e) {
    e.printStackTrace();
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        commission_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        narrative = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(715, 400));
        setResizable(false);

        jLabel1.setText("Employee :");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        commission_name.setText("0.00");
        commission_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                commission_nameKeyReleased(evt);
            }
        });

        jLabel3.setText("Allowance Type: ");

        jLabel2.setText("Earned Amount :");

        narrative.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                narrativeKeyReleased(evt);
            }
        });

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(narrative)
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(commission_name, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commission_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(narrative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        try{
        if(jList1.isSelectionEmpty()){
        JOptionPane.showMessageDialog(null, "Please select Employee!");
        }else{
        String ename = jList1.getSelectedValue().toString();
          
        String[] parts = ename.split(" ",2);
        String part1 = parts[0]; // 004
        String part2 = parts[1]; 
        String e_id = "select * from employee where personal_file_number = '"+part1+"'";
        ps1 = conn.prepareStatement(e_id);
        rs1 = ps1.executeQuery();

        if(rs1.next()){
        String eid = rs1.getString("id");
        if(commission_name.getText().matches("\\-?\\d+") == false && commission_name.getText().matches("^[-+]?\\d+(\\.{0,1}(\\d+?))?$") == false) {
        JOptionPane.showMessageDialog(null,"Please provide numbers only for basic pay!");
        }else{
            String emp_exist = "select * from employee_commission where employee_id='"+eid+"'";
            ps2 = conn.prepareStatement(emp_exist);
            rs2 = ps2.executeQuery();
        if(rs2.next() && part1.equals(eid)){
        String upd = "update employee_commission set employee_id='"+eid+"',commission='"+commission_name.getText()+"',narrative='"+narrative.getText()+"',updated_at=NOW() where employee_id = '"+eid+"'";
        ps3 = conn.prepareStatement(upd);
        ps3.execute();
     
        JOptionPane.showMessageDialog(null, "Successfully updated employee commission!");
        }else{
        String ins = "insert into employee_commission (employee_id,commission,narrative,created_at)values('"+eid+"','"+commission_name.getText()+"','"+narrative.getText()+"',NOW())";
        ps4 = conn.prepareStatement(ins);
        ps4.execute();
        JOptionPane.showMessageDialog(null, "Successfully inserted employee commission!");
        }
        }
        }
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_okActionPerformed

    private void commission_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commission_nameKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
        if(jList1.isSelectionEmpty()){
        JOptionPane.showMessageDialog(null, "Please select Employee!");
        System.out.println("nothing");
        }else{
        String ename = jList1.getSelectedValue().toString();
        int index = jList1.getSelectedIndex();
          
        String[] parts = ename.split(" ",2);
        String part1 = parts[0]; // 004
        String part2 = parts[1]; 
        String e_id = "select * from employee where personal_file_number = '"+part1+"'";
        ps1 = conn.prepareStatement(e_id);
        rs1 = ps1.executeQuery();

        if(rs1.next()){
        String eid = rs1.getString("id");
        if(commission_name.getText().matches("\\-?\\d+") == false && commission_name.getText().matches("^[-+]?\\d+(\\.{0,1}(\\d+?))?$") == false) {
        JOptionPane.showMessageDialog(null,"Please provide numbers only for basic pay!");
        }else{
            String emp_exist = "select * from employee_commission where employee_id='"+eid+"'";
            ps2 = conn.prepareStatement(emp_exist);
            rs2 = ps2.executeQuery();
        if(rs2.next()){
        String upd = "update employee_commission set employee_id='"+eid+"',commission='"+commission_name.getText()+"',narrative='"+narrative.getText()+"',updated_at=NOW() where employee_id = '"+eid+"'";
        ps3 = conn.prepareStatement(upd);
        ps3.execute();
     
        JOptionPane.showMessageDialog(null, "Successfully updated employee commission!");
        }else{
        String ins = "insert into employee_commission (employee_id,commission,narrative,created_at)values('"+eid+"','"+commission_name.getText()+"','"+narrative.getText()+"',NOW())";
        ps4 = conn.prepareStatement(ins);
        ps4.execute();
        JOptionPane.showMessageDialog(null, "Successfully inserted employee commission!");
        }
        }
        }
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_commission_nameKeyReleased

    private void narrativeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_narrativeKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
        if(jList1.isSelectionEmpty()){
        JOptionPane.showMessageDialog(null, "Please select Employee!");
        System.out.println("nothing");
        }else{
        String ename = jList1.getSelectedValue().toString();
        int index = jList1.getSelectedIndex();
          
        String[] parts = ename.split(" ",2);
        String part1 = parts[0]; // 004
        String part2 = parts[1]; 
        String e_id = "select * from employee where personal_file_number = '"+part1+"'";
        ps1 = conn.prepareStatement(e_id);
        rs1 = ps1.executeQuery();

        if(rs1.next()){
        String eid = rs1.getString("id");
        if(commission_name.getText().matches("\\-?\\d+") == false && commission_name.getText().matches("^[-+]?\\d+(\\.{0,1}(\\d+?))?$") == false) {
        JOptionPane.showMessageDialog(null,"Please provide numbers only for basic pay!");
        }else{
            String emp_exist = "select * from employee_commission where employee_id='"+eid+"'";
            ps2 = conn.prepareStatement(emp_exist);
            rs2 = ps2.executeQuery();
        if(rs2.next()){
        String upd = "update employee_commission set employee_id='"+eid+"',commission='"+commission_name.getText()+"',narrative='"+narrative.getText()+"',updated_at=NOW() where employee_id = '"+eid+"'";
        ps3 = conn.prepareStatement(upd);
        ps3.execute();
     
        JOptionPane.showMessageDialog(null, "Successfully updated employee commission!");
        }else{
        String ins = "insert into employee_commission (employee_id,commission,narrative,created_at)values('"+eid+"','"+commission_name.getText()+"','"+narrative.getText()+"',NOW())";
        ps4 = conn.prepareStatement(ins);
        ps4.execute();
        JOptionPane.showMessageDialog(null, "Successfully inserted employee commission!");
        }
        }
        }
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_narrativeKeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        try{
        int ename = jList1.getSelectedIndex();
          
        String list_click = (jList1.getModel().getElementAt(ename).toString());
        
        String e_id = "select * from employee_commission where id = '"+list_click+"'";
        ps5 = conn.prepareStatement(e_id);
        rs5 = ps5.executeQuery();
        if(rs5.next()){
        String add1=rs5.getString("commission");
        commission_name.setText(add1);
        String add2=rs5.getString("narrative");
        narrative.setText(add2);
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        // TODO add your handling code here:
        try{
        String ename = jList1.getSelectedValue().toString();
          
        String[] parts = ename.split(" ",2);
        String part1 = parts[0]; // 004
        String part2 = parts[1]; 
        String e_id = "select * from employee where personal_file_number = '"+part1+"'";
        ps1 = conn.prepareStatement(e_id);
        rs1 = ps1.executeQuery();
        if(rs1.next()){
        String eid = rs1.getString("id");
        String emp_exist = "select * from employee_commission where employee_id='"+eid+"'";
            ps2 = conn.prepareStatement(emp_exist);
            rs2 = ps2.executeQuery();
        if(rs2.next()){
        String add1=rs2.getString("commission");
        commission_name.setText(add1);
        String add2=rs2.getString("narrative");
        narrative.setText(add2);
        }
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jList1KeyPressed

    public void close(){
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basic_comission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basic_comission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basic_comission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basic_comission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basic_comission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField commission_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField narrative;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
